### ISSUE TITLE
It works fine but little bit slow

### ISSUE THREAD

**Issue by st1905** [RiFi2k/unlimited-tethering#1]
Hi,

I get 16 Mbps when i use my phone but when i use ssh tunnel with sshuttle i get around 3 Mbps, its still much better than the throttled speeds of 500kbps-1.2Mbit etc.. but its nowhere near 16Mbit.

You also forgot to mention that for sshuttle, one needs to install Python2 on the phone via Termux. You also need to create a symbolic link for the binary python2.7 to python(On the phone) for the sshuttle to function on the PC.

My setup is

Client = FreeBSD

Server = Android 9

**Comment by RiFi2k** [comment]
Your totally right on the Python and the symbolic link I glossed over that for sure I'll add it.

Speaking to the 16 -> 3 loss that actually seems to be pretty on point with what I saw. Except I get ~110 Mbps on my phone and when I would run it after the tunnel I would be at 24-30 ish. So it seems like realistically your look at about 1/5th the speed at the end of the day. I never spent any time trying to optimize so I would be open to any suggestions on what that might look like.
