### ISSUE TITLE
help setting up in windows 10

### ISSUE THREAD

**Issue by chiz419** [RiFi2k/unlimited-tethering#2]
I was wondering if you'd be able to help me out with setting this up using openssh in powershell on windows 10? 

thanks!

**Comment by RiFi2k** [comment]
Unfortunately I have nothing at all in my house with Windows installed on it so I'm downloading a VM right now so I can run through the steps on Win10 for anyone who needs it.

If you wanna get started now my recommendation would be [Chocolatey](https://chocolatey.org/packages/openssh/8.0.0.1) package manager. https://gitlab.com/DarwinJS/ChocoPackages/tree/master/openssh

I took a 5 second look and this might be a good fit for the tunnel but I haven't tried or really read the code. https://tsherlock.tech/2019/03/13/simple-ssh-tunnel-auto-reconnect-using-putty-and-powershell/

Maybe this? https://persistentssh.com/

I'll circle back when I have the VM.

**Comment by RiFi2k** [comment]
@chiz419 I added information to the README which should help you get this done on Windows. Can you check to see if that works out for you?
